# Generated by Django 3.0.4 on 2020-04-11 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('age', models.IntegerField()),
                ('complexion', models.CharField(max_length=10)),
                ('job', models.CharField(max_length=30)),
            ],
        ),
    ]
